# Generated by Django 2.0.6 on 2018-06-21 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variety', models.CharField(choices=[('B', 'Bug'), ('F', 'Feature')], max_length=1)),
                ('upvotes', models.IntegerField(default=0)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_verified', models.DateField(blank=True)),
                ('author', models.CharField(blank=True, max_length=20)),
                ('verified', models.BooleanField(default=False)),
                ('status', models.CharField(default='to do', max_length=6)),
                ('issue', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
