# Generated by Django 2.0.6 on 2018-06-21 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='date_verified',
            field=models.DateField(),
        ),
    ]
