# Generated by Django 2.0.6 on 2018-06-21 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_auto_20180621_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='date_verified',
            field=models.DateField(null=True),
        ),
    ]
